name: Publish to GitHub Packages

on:
  workflow_dispatch: # for manual trigger
  release:
    types: [published] # triggers when release-please creates a release

jobs:
  publish:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      id-token: write
      packages: write
    steps:
      - uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@2028fbc5c25fe9cf00d9f06a71cc4710d4507903 # v6.0.0
        with:
          node-version: '18'
          registry-url: 'https://npm.pkg.github.com'
          scope: '@nominal-io'

      - name: Install dependencies
        run: npm ci

      - name: Build
        run: npm run compile

      - name: Run tests
        run: npm test
        env:
          MOCHA_THROW_DEPRECATION: false

      - name: Publish to GitHub Packages
        run: npm publish
        env:
          NODE_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
